### ISSUE TITLE
Disable italics

### ISSUE THREAD

**Issue by mathdothings** [wuelnerdotexe/vim-enfocado#10]
I'm new to vim and can't find a way to disable italics on this theme and will really appreciate if someone help me with this. Thanks.
Obs: I just want to disable all italics from everything.

**Comment by wuelnerdotexe** [comment]
Hi @mathdothings - thanks for using **Enfocado**. You can always modify what you like about this theme by following the [customization instructions](https://github.com/wuelnerdotexe/vim-enfocado#customization). In this case, to disable all italics, use the following snippet in your `.vimrc` or `init.vim`:
```vim
augroup enfocado_customization
  autocmd!
    autocmd ColorScheme enfocado ++nested highlight Comment cterm=nocombine gui=nocombine
    autocmd ColorScheme enfocado ++nested highlight Function cterm=nocombine gui=nocombine
    autocmd ColorScheme enfocado ++nested highlight FunctionBuiltin cterm=nocombine gui=nocombine
augroup END
```
Close this problem, only if you get the result you expect :)

**Comment by mathdothings** [comment]
I even didn't know about this customization. I really appreciate your help. Thanks. Closing the issue.
