### ISSUE TITLE
Make the background transparent

### ISSUE THREAD

**Issue by fabianmolinab** [wuelnerdotexe/vim-enfocado#11]

**Comment by wuelnerdotexe** [comment]
To make the **Enfocado** background transparent, you just need to add the example code snippet from the [customization](https://github.com/wuelnerdotexe/vim-enfocado#customization) section of this project to your `.vimrc` or `init.vim`, which is as follows:

```vim
augroup enfocado_customization
  autocmd!
    autocmd ColorScheme enfocado ++nested highlight Normal ctermbg=NONE guibg=NONE
augroup END
```

Please close this issue if it works as expected. Thanks.
