### ISSUE TITLE
No italics

### ISSUE THREAD

**Issue by lokesh-krishna** [wuelnerdotexe/vim-enfocado#2]
Just discovered this theme and am in love with it and Selenized. Love the idea of using italics tastefully but with the default setup, I don't get italics for the expected highlight groups. I am using Treesitter and do get italics with other colorschemes such as [Moonfly](https://github.com/bluz71/vim-moonfly-colors). What might be going on?

**Comment by lokesh-krishna** [comment]
My bad, I wasn't using the activation command recommended in the readme.

**Comment by wuelnerdotexe** [comment]
Oh my gosh I hadn't seen your problem. I just added a comment to that part of the [README](https://github.com/wuelnerdotexe/vim-enfocado#colorscheme) to make sure all plugins are colored. Good to know that you like **Enfocado**. 😃

**Comment by lokesh-krishna** [comment]
Awesome :D
