### ISSUE TITLE
enfocado+LunarVim = awesome

### ISSUE THREAD

**Issue by ghost** [wuelnerdotexe/vim-enfocado#3]
Thought you might enjoy the LunarVim project, which takes a wonderfully opinionated approach to Neovim setup, that I think pairs nicely with your theme. I have been using selenized-black with LunarVim for a while now, and vim-enfocado is yet another upgrade.

They have a colorscheme repo, you may be interested in contributing: https://github.com/LunarVim/Colorschemes

Thanks for the great theme!

**Comment by wuelnerdotexe** [comment]
I have reviewed the rules to contribute and be able to implement **Enfocado for LunarVim** and unfortunately it is very restrictive and does not allow to apply the main **Enfocado** functionalities such as **Human Writing**. Thank you for choosing Enfocado !! 👁️
