### ISSUE TITLE
Italics doesn't work

### ISSUE THREAD

**Issue by aravind2612krishna** [wuelnerdotexe/vim-enfocado#4]
Thanks for the great theme. 
Even though the italics worked when I first installed the plugin, it is not working in subsequent nvim invocations. I'm not sure what I changed to cause it to stop working.
Worth mentioning that Italics works in other treesitter colorschemes like solarized. 
I have termguicolors and activate using the autocmd as in Readme. 

Any way I can debug this?

**Comment by aravind2612krishna** [comment]
Here is a sample of highlight test, if it helps
![image](https://user-images.githubusercontent.com/3424615/148167137-e4cffbb7-dbfd-47cf-bd06-b013c435e785.png)
None of the Enfocado groups have italics in them.

**Comment by aravind2612krishna** [comment]
Unfortunately this was because I had disabled highlighting in treesitter config. Once it was enabled, I'm able to see the italics.

**Comment by wuelnerdotexe** [comment]
@aravind2612krishna sorry for not responding quickly to the problem, but I'm glad you found the solution. Thank you for choosing **Enfocado** !! 🎉
