### ISSUE TITLE
Colors in the carbon.nvim plugin are cleared.

### ISSUE THREAD

**Issue by datwaft** [wuelnerdotexe/vim-enfocado#5]
The plugin [SidOfc/carbon.nvim](https://github.com/SidOfc/carbon.nvim) has some highlights that are currently being cleared by Enfocado.

Here is the list of highlights.

```
- CarbonDir
- CarbonFile
- CarbonExe
- CarbonSymlink
- CarbonBrokenSymlink
- CarbonIndicator
```

It would be delightful if Enfocado supported carbon.nvim.

Thanks for your help. I love Enfocado 😄.

**Comment by wuelnerdotexe** [comment]
Hi @datwaft, thanks for contributing to **Enfocado** by reporting this bug.

It seems that the colorscheme removes the highlights made with the lua API `vim.api.nvim_buf_add_highlight` when it is activated using the vim auto command `autocmd VimEnter * ++nested colorscheme enfocado`. The possible solution (hoping to see that it doesn't break anything else) is to simply activate the colorscheme, using the `colorscheme enfocado` command.

Thank you for choosing **Enfocado** !! 🙌

**Comment by wuelnerdotexe** [comment]
I will release an update ceasing to recommend the auto command in question, arguing this bug. And sorry for the delay, and for my very bad English. 😅
Let me know if the proposed solution helped you...

**Comment by datwaft** [comment]
Thanks for your help!

It seems to work properly now:
![image](https://user-images.githubusercontent.com/37723586/159377699-9692af60-b10f-4ca8-a953-3d39c8ac6581.png)

Btw, if you could support [nvim-ts-rainbow](https://github.com/p00f/nvim-ts-rainbow) in your colorscheme as you do with [rainbow](https://github.com/luochen1990/rainbow) it would be great. As you can see in the screenshot the parentheses' first level is using the color red, and that goes against your colorscheme philosophy.

The issue can be closed now, I think.

**Comment by datwaft** [comment]
Btw, I am also a native Spanish speaker, so don't worry about your English. It's great!

**Comment by wuelnerdotexe** [comment]
Hello again @datwaft! I've posted the update your issue report mentions and fixed the correct command for colorscheme activation as well as added support for [nvim-ts-rainbow](https://github.com/p00f/nvim-ts-rainbow). Now we can close this thread... 🎉

**Comment by datwaft** [comment]
Thanks!
