### ISSUE TITLE
Enfocado always overrides `Whitespace` highlight even if the plugin is not active

### ISSUE THREAD

**Issue by datwaft** [wuelnerdotexe/vim-enfocado#8]
### Discussed in https://github.com/wuelnerdotexe/vim-enfocado/discussions/7

<div type='discussions-op-text'>

<sup>Originally posted by **datwaft** August 14, 2022</sup>
See the following screenshot:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/184556507-271cad21-fe71-48a8-a85b-f6bedc5be9dd.png">

How do I remove the color yellow that highlights tabs and spaces at the end of the line?</div>

See https://github.com/wuelnerdotexe/vim-enfocado/discussions/7#discussioncomment-3417117 for more information.

**Comment by wuelnerdotexe** [comment]
There is already an update on the way to fix this along with other additions.

--
To whom it may be useful: visit discussion #7  opened by @datwaft to find out the source of this problem.

**Comment by wuelnerdotexe** [comment]
@datwaft the update is already in the `main` branch, please proceed to close this issue only if your problem has been solved.

**Comment by datwaft** [comment]
It works perfectly now, thanks!
