### ISSUE TITLE
Some kind icons in `nvim-cmp` are displayed in italic

### ISSUE THREAD

**Issue by datwaft** [wuelnerdotexe/vim-enfocado#9]
I have been trying to configure `nvim-cmp` to display the kind icons in the completion popup, and for that I am following [this documentation](https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#basic-customisations).

One small pet peeve for me is that the kind icon for some kinds is displayed in italic.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/189496357-37137bec-c911-4640-b81b-16208132c6e1.png">

I have been defining the following highlight groups to remove the italic from the icons:

```vim
highlight! CmpItemKindEvent guifg=#ff81ca
highlight! CmpItemKindFunction guifg=#83c746
highlight! CmpItemKindMethod guifg=#83c746
```

And here is the result:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/189496497-273558bf-72a4-4d9a-ad7c-fb509955a3ff.png">

[Here](https://github.com/datwaft/nvim.conf/blob/ef87e9594c058aec2fdb2c8e17b112d0cd5744bf/fnl/conf/pack/colorscheme.fnl#L54-L56) is a permalink of my configuration.

**Comment by wuelnerdotexe** [comment]
Hi again @datwaft - thanks for once again reporting a new issue, after several days (sorry) i fixed it, hope it works for you and close this issue.

Thank you for continuing to use **Enfocado**. Your setup looks very elegant. 🤩
